### ISSUE TITLE
Switches repeating every 5 mins.

### ISSUE THREAD

**Issue by ozzyjah** [rayzurbock/BigTalker2#1]
Hi, I am having a problem with my switches. When operating the switch the app says "turned on" then repeats itself every 5 minutes. It does this in both the on and off position. Although it only happens with my TP-Link switches. 
My Energenie switches only speak once for each operation.

**Comment by rayzurbock** [comment]
Perhaps the TP-Link's are being polled every 5 minutes and regenerating an ON event or OFF event (repeating the last change).  This will either be a switch issue or an issue with the device handler for it in SmartThings.  BigTalker2 only activates when it's been told there has been an event occur that it was subscribed to (ie: ON/OFF).  For some reason it sounds like it's being told an event occurred even though the state of the switch really didn't change.

**Comment by ozzyjah** [comment]
Hi, thanks for the reply. I had to turn it off in the end as it just keeps repeating it. I tried again a couple of days ago and it is still doing it, so I have just deleted the switches from bigtalker2. Everything else works fine.
