### ISSUE TITLE
Repeat on event

### ISSUE THREAD

**Issue by frankfdu** [rayzurbock/BigTalker2#14]
I hope this is the right place to specify this question but is there a way to repeat a message on an interval in BigTalker2? (ie repeat the door is open if the status hasn't changed every few minutes)

I can't find the place to do so...

**Comment by rayzurbock** [comment]
BigTalker2 speaks at the time an event occurs only at this time.  It does not repeat the event notification unless the event reoccurs (ie: speak on door open, door closes, door opens again).
