### ISSUE TITLE
Unable to create event groups

### ISSUE THREAD

**Issue by craigcolley35** [rayzurbock/BigTalker2#2]
I recently started trying to use Bigtalker 2 and have not been able to add event groups. Each time I try,  I just get an error in the smartthings app saying "sorry,  there was an unexpected error". I'm setup with LANNOUNCER and can successfully send audio from ST to my android device running ST.
![screenshot_2018-02-27-22-50-55](https://user-images.githubusercontent.com/13879094/36770596-c139bfe8-1c10-11e8-8cf5-4375ccc70e3d.png)

**Comment by rayzurbock** [comment]
Is this still an issue?
Can you login to the IDE and go to Live Logging while you click "Add Event Group" and see if there is an error thrown in the logs?
https://graph.api.smartthings.com/ide/logs

**Comment by adrian97c** [comment]
![12d5df24-8a16-4f7f-8961-5aa82a37223d](https://user-images.githubusercontent.com/35380549/37380913-14ae53d6-2711-11e8-871a-ed14b8e3404a.png)

**Comment by rayzurbock** [comment]
Did you install the child app code as well? (BigTalker2-Child). If so, did you save and publish the parent app and save the child app?

Did you make any changes to the code (ie: to enable multiple installs, etc)

**Comment by mmenegaz** [comment]
I recently change for the new version and I cant add a event group as well. Follow my live logging screen shot!
![untitled](https://user-images.githubusercontent.com/23272469/40866243-0b0fe870-65d3-11e8-8354-631ae55fce31.png)

**Comment by rayzurbock** [comment]
This will happen if the child app is not saved as well. If it still doesn't work go ahead and try saving the child app and publishing as well.

**Comment by rayzurbock** [comment]
Did my last comment help resolve this issue?
