### ISSUE TITLE
Music after announcement

### ISSUE THREAD

**Issue by sonnyg77** [rayzurbock/BigTalker2#3]
Looking for some help please,
Ive set up Bigtalker and VLCThing it is working fine however i have an issue, the music does not resume after announcements.
I have the settings set to attempt to resume music in the main default and for each set of messages,  my media is loaded into the "my media" section of VLC,  when playing music and an announcement comes through,  the music stops and the message starts, when finished i get 5 seconds of the next track and it stops, i can press play on the app it plays but then after another message i get the same 5 seconds of the next track before it stops again.
The same happens if no music is playing,  after the message i get 5 seconds of music?
is there anything else i should have selected in either in Bigtalker or VLC.
Many thanks 
Sonny

**Comment by rayzurbock** [comment]
Unfortunately, BigTalker relies on the Device Handler (VLCThing in this case) to handle the resume part.  BigTalker sends a call to the device handler "playTextAndResume" along with data to speak, etc.  The device handler then does all of the magic with causing the speech device to play/resume.
VLCThing is developed by STCommunity @Geko.  You may need to ask him about the playTextAndResume / playTrackAndResume function not working as expected.

**Comment by sonnyg77** [comment]
Many Thanks rayzurbock,  i will get onto that now.
Thank you
