### ISSUE TITLE
error java.lang.NullPointerException @line 1338 (processDayRestriction)

### ISSUE THREAD

**Issue by rickfrancis** [rayzurbock/BigTalker2#8]
Getting null pointer exceptions when the on switch tries to kick off the bigtalker2 app.

**Comment by rayzurbock** [comment]
Please see this response and see if it resolves your issue as well
https://community.smartthings.com/t/release-bigtalker-2-x/118105/159

**Comment by rayzurbock** [comment]
@rickfrancis  Did the link that I posted help you resolve the issue?
